trigger:
  batch: true
  branches:
    include:
    - master

resources:
- repo: self

variables:
  commitId: '$(Build.SourceVersion)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build image and push it to DockerHub
      inputs:
        containerRegistry: 'teamdigitalesa'
        repository: 'italia/developers-italia-onboarding'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(commitId)
          latest
